[package]
name = "LocalSuperSearch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
home = "0.5.11"
keyword_extraction = "1.5.0"
queues = "1.1.0"
sqlite = "0.37.0"
stop-words = "0.8.1"
